version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    ignore:
      # The node version for the action is set to 16
      - dependency-name: "@types/node"
        versions: ">16"
